/**
 * Footer.jsx - Site footer
 * 
 * Appears at the bottom of every page with:
 * - Copyright information
 * - RSS feed link
 * - Optional social links
 */

import { Link } from 'react-router-dom';

function Footer() {
  // Get current year for copyright notice
  const currentYear = new Date().getFullYear();
  
  return (
    <footer className="site-footer">
      <div className="container">
        <div className="footer-content">
          {/* Copyright notice */}
          <div className="footer-copyright">
            © {currentYear} Public Presence. All rights reserved.
          </div>
          
          {/* Footer navigation links */}
          <div className="footer-links">
            {/* RSS feed link - allows readers to subscribe
                The RSS file is generated by the prebuild script */}
            <a href="/rss.xml" target="_blank" rel="noopener noreferrer">
              RSS Feed
            </a>
            
            {/* Optional: Add your social media links here
                Example: LinkedIn, Twitter, GitHub, etc. */}
            {/* 
            <a href="https://linkedin.com/in/yourprofile" target="_blank" rel="noopener noreferrer">
              LinkedIn
            </a>
            <a href="https://twitter.com/yourhandle" target="_blank" rel="noopener noreferrer">
              Twitter
            </a>
            */}
          </div>
        </div>
      </div>
    </footer>
  );
}

export default Footer;
